meta_product_name: "Surelytics"
meta_title: "Surelytics | Your digital analytics under control"
meta_description: "ðŸŽ¸Become a webanalytics rockstar thanks to Surelytics ==> Try it nowðŸŽ¸"
meta_image: "surelytics_homeboy.png"
twitter_account: "@aristweet"
